### ISSUE TITLE
Two subsequent git-push to a dataverse dataset in filetree mode break it

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#143]
It will not replace the exported files, but rather add renamed copies -- which breaks the special remote logic

![image](https://user-images.githubusercontent.com/136479/177821700-fc908e4a-a56a-4856-861d-04096407ca20.png)

**Comment by bpoldrack** [comment]
Just FTR when addressing this: IIRC this may depend on whether the previous push was "published" in between.

**Comment by mih** [comment]
In my case it was two subsequent git-push calls was nothing inbetween.

**Comment by bpoldrack** [comment]
Looking into this to figure out when and how exactly to replace instead.

**Comment by mih** [comment]
I don't think calling a replace method is the (only) fix to be made. This is happening also when nothing is changed at all. Nothing should be done in this case, not replacing X with X. I think it is worth looking into improving the file identify records. Related: #146

**Comment by bpoldrack** [comment]
Yes, I am aware. Also: We can't even replace w/o keeping track of file identifiers.
Hence, need to think about how to do that best.

**Comment by bpoldrack** [comment]
> This is happening also when nothing is changed at all.

Just noting an observation on this: a `datalad push . --to REMOTE` w/o any changes not only results in the repo itself being pushed again (under `.datalad/dot_git`), but in fact everything underneath `.datalad`, while files outside seem unaffected. Since `push` should figure what needs pushing, I suppose some check isn't quite right or somehow torpedoed.
Double-checking whether the leading dot issue leads to this.
