### ISSUE TITLE
Key operations non-export mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad-dataverse#204]
Given #177 this issue is scope-limited to non-export mode.

We implement the operations: CHECKPRESENT, STORE, RETRIEVE, REMOVE. They are detailed below. 

All operations are key-based, i.e. they need to be able to work with only a key given. At present the implementation also stores the dataverse `fileId` as a git-annex key state. The utility of that is explored here.

Dataverse datasets can be versioned, i.e. a particular state is "published" and becomes immutable afterwards. Further modifications create a new draft/version.

#### Current implementation

A `key` is translated to a `fileId` by looking up its `STATE`, afterwards the latest or full dataset content listing is inspected whether the `fileId` is listed.

If no `fileId` is known, the `key` is interpreted as a `filepath` and matched against the same dataset content listing.

#### Alternative implementations

There seems to be no benefit from the `fileId` lookup. If a dataset content listing is around, a `key`  can always be matched by its name as a `filename`.

If a `fileId` is considered needed/useful for other operations, it would become apparent duringany lookup performed here, and could be stored in a key's `STATE`.

#### Current implementation

A `key` is deposited using its name as `filename`. However, the implementation of an upload is shared with the one an export remote is using, so additional requests are made that account for file replacement. The reported `fileId` is recorded as the key's `STATE`.

#### Alternative implementation

A dedicated implementation (not shared with export can be simpler). There is no need for replacement detection. If a key exists, it can assumed to be identical in content. If that is not the case (URL keys, XDLRA keys), it is not the responsibility of this remote implementation to handle that, because it is undefined what should be done.

#### Current implementation

A `fileId` is needed for download. It is either looked up from the key's `STATE`, or by parsing the dataset content listing.

#### Alternatve implementation

If no `fileId` records would be available, a `fileId` lookup could be performed solely with the content listing.

#### Current implementation

Also see #183.

The implementation is shared with export-mode.

A `fileId` is needed for the eventual `DELETE` request. It is looked up from a key's `STATE` or by key-path from the dataset content listing. Afterwards, the deletion is confirmed by inspecting an updated dataset content listing.

Due to the impact of dataverse dataset versions potentially preventing a deletion it is not guaranteed. The is no signaling about that other than a debug message and an unsetting of a `fileId` record in a key's `STATE`.

#### Alternatve implementation

Decision making could always and unconditionally be done based on the dataset content listing (that the current implementation pretty much always retrieves).

If a key-file is not part of the `:latest` dataset state, it can never be deleted. If the latest state happens to be a published version (`.is_released`) it can also not be delete. The is no need to make a dedicated request for that.

If a key-file appears to be deletable, the response status of the request would tell if it was successful. There should be no need for a follow-up listing request.

## Conclusion

The analysis above seems to indicate that the local tracking of `fileId` records is unnecessary, and could be removed to reduce implementation complexity. Complexity is further reduced by separating export and non-export mode logic.

Removing `fileId` records does impact retrieve performance. Rather than a local `GETSTATE` it would require a dataset content listing, potentially covering all versions.

However, at present `fileId` `STATE` records are only created on upload/`STORE`. So the available performance boost is limited. If the cost of maintaining `fileId` records is to be paid, they should also be created on `CHECKPRESENT` to minimize the frequency with which dataset listings need to be obtained.

**Comment by bpoldrack** [comment]
I agree.

`fileID` is indeed introduced to be able to support versioned export remotes (#146). Once on record one may as well use it in non-export mode to potentially save another lookup (as you pointed out), but with the intention to split the implementation, `fileID` can be ignored for non-export. Agreed.

One thing to point out:

> STORE
> If a key exists, it can assumed to be identical in content. If that is not the case (URL keys, XDLRA keys), it is not the responsibility of this remote implementation to handle that, because it is undefined what should be done.

> REMOVE
> Due to the impact of dataverse dataset versions potentially preventing a deletion it is not guaranteed. The is no signaling about that other than a debug message and an unsetting of a fileId record in a key's STATE.

Those two belong together. If annex decides to replace such a key in non-export mode, it would need a "successful" REMOVE, despite the old version of the file not actually being deletable. And as long as `fileId` is used for lookup, that would still need to go in order to match the "new version of the key".
Just to lay out the reasoning as I recall it.


What is a bit unclear to me is your last point:

> If the cost of maintaining fileId records is to be paid, they should also be created on CHECKPRESENT to minimize the frequency with which dataset listings need to be obtained.

While I'd agree that it could be updated/created on CHECKPRESENT, "the frequency with which dataset listings need to be obtained" seems to suggest that there are repeated requests. There's only one request for the latest version and one for all others (both lazy - see `files_latest`  and `files_old`). Changes can only happen to latest, obviously and are tracked locally. There's no update during runtime of the special remote currently. This is, of course, making an assumption (that there's no parallel modification) and one may debate that and come up with a different caching strategy, but I just want to make that clear since I am not sure whether there's a misconception hiding here.

**Comment by mih** [comment]
@bpoldrack thanks for the feedback. Responding to

> seems to suggest that there are repeated requests

Yes there are. Not within a single invocation of the special remote, but across. It would be necessary to minimize the frequency across, by creating such records that persist across special remote invocation.

**Comment by bpoldrack** [comment]
Ok. Thx for clarification.
