### ISSUE TITLE
Implement credential retrieval for create-sibling-dataverse

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-dataverse#50]
Right now, this just gets the token from the test environment.
Proper implementation should rely on `CredentialManager` from `datalad-next` and consider all the respective configurations.

In `create_sibling_dataverse.py` is a to be implemented function `_get_api_token` for that.

**Comment by adswa** [comment]
I'm taking a look into this

**Comment by adswa** [comment]
It still needs an integration with the special remote. @mih is working on that as far as I know

**Comment by mih** [comment]
Once the command works, I can generalize the implementation to also cover it.

**Comment by mih** [comment]
It seems that the current implementation already uses the credential manager https://github.com/datalad/datalad-dataverse/blob/f33c68fd3eab0c7dfca9e8c2ab091d9422e0ca52/datalad_dataverse/create_sibling_dataverse.py#L397 to retrieve credentials. Hence I am closing this issue.

However, I filed #113, because credentials are not a stored at all, forcing users to reenter credentials over and over.
